import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDown, ArrowRight, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { images, pageHead, records } from '@/lib/content';

export const Route = createFileRoute('/')({
  head: () => pageHead('Explore the science at the ends of the Earth', 'Discover India’s polar expeditions, research sources and field stories through a clear, connected public experience.'),
  component: Home,
});

function Home() {
  return <main>
    <section className="hero"><img className="hero-image" src={images.hero} alt="Antarctic ice cliffs and a research vessel on the water" width={1920} height={1080}/><div className="hero-content page-container"><div className="hero-index">An open window into polar science</div><h1>Science at the<br/>ends of the <em>Earth.</em></h1><p>Explore the expeditions, discoveries and people shaping our understanding of the polar regions.</p><Button asChild variant="hero" size="lg"><Link to="/expeditions">Explore expeditions <ArrowUpRight/></Link></Button><div className="hero-bottom"><span>PolarConnect / India’s polar story</span><span className="scroll-cue">Scroll to discover <ArrowDown size={15}/></span></div></div></section>
    <section className="section page-container"><div className="intro-grid"><div><div className="section-kicker"><span>01</span><span>Our purpose</span></div><h2 className="editorial-title">The story behind the <em>science.</em></h2></div><div><p>From the ice sheets of Antarctica to the waters of the Southern Ocean, polar research helps us understand a changing planet. PolarConnect brings the stories and their sources together in one place.</p><Link to="/about" className="text-link">Get to know the platform <ArrowUpRight size={16}/></Link></div></div></section>
    <div className="feature-band"><div className="feature-grid page-container"><div className="feature-item"><span className="feature-number">01</span><h3>Follow the journey</h3><p>Discover where expeditions go, what they study, and what happens beyond the field.</p></div><div className="feature-item"><span className="feature-number">02</span><h3>Find the evidence</h3><p>Move from an accessible story to reports, observations and original research sources.</p></div><div className="feature-item"><span className="feature-number">03</span><h3>Share responsibly</h3><p>Understand where information comes from and follow the source’s rights and access terms.</p></div></div></div>
    <section className="section page-container"><div className="section-kicker"><span>02</span><span>Explore the regions</span></div><div className="section-heading"><h2>Beyond the map.<br/><em>Into the field.</em></h2><Link to="/expeditions" className="text-link">All expeditions <ArrowUpRight size={16}/></Link></div><div className="story-grid"><Link to="/expeditions/southern-ocean" className="story-card"><div className="story-image"><img src={images.ocean} alt="Research vessel moving through Southern Ocean sea ice" loading="lazy"/></div><div className="story-meta"><span>01 / Southern Ocean</span><span>Expedition focus</span></div><h3>Where the ocean meets the ice</h3><p>Trace the questions, voyages and research behind a vital part of our planet.</p><span className="story-cta">Explore the journey <ArrowUpRight size={15}/></span></Link><Link to="/expeditions/antarctica" className="story-card"><div className="story-image"><img src={images.station} alt="Polar research station surrounded by Antarctic snow and mountains" loading="lazy"/></div><div className="story-meta"><span>02 / Antarctica</span><span>Research focus</span></div><h3>Life and science on the ice</h3><p>Get closer to the stations and fieldwork that make long-term polar observations possible.</p><span className="story-cta">Explore the journey <ArrowUpRight size={15}/></span></Link></div></section>
    <section className="dark-section section"><div className="page-container"><div className="section-kicker"><span>03</span><span>Knowledge library</span></div><div className="section-heading"><h2>Every discovery has <em>a source.</em></h2><div><p>Find original research through a curated doorway to authoritative polar information.</p><Link to="/library" className="text-link spaced-link">Browse the library <ArrowUpRight size={16}/></Link></div></div><div className="source-grid">{records.slice(0,3).map((item,i)=><a className="source-tile" key={item.id} href={item.url} target="_blank" rel="noreferrer"><span>0{i+1} / {item.type}</span><h3>{item.title}</h3><div><span>{item.source}</span><ArrowUpRight size={18}/></div></a>)}</div></div></section>
    <section className="section quote-section page-container"><div className="section-kicker"><span>04</span><span>A connected perspective</span></div><blockquote>“From scattered records to a living account of polar science.”</blockquote><p>Research deserves to be discoverable, understandable and always connected to the evidence behind it.</p><Link to="/stories" className="text-link spaced-link">Read field stories <ArrowRight size={16}/></Link></section>
  </main>;
}
