/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExpeditionsRouteRouteImport } from './routes/expeditions/route'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as StoriesRouteRouteImport } from './routes/stories/route'
import { Route as ExpeditionsIndexRouteImport } from './routes/expeditions/index'
import { Route as ExpeditionsAntarcticaRouteImport } from './routes/expeditions/antarctica'
import { Route as ExpeditionsSouthernOceanRouteImport } from './routes/expeditions/southern-ocean'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesReadingTheIceRouteImport } from './routes/stories/reading-the-ice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRouteRoute = ExpeditionsRouteRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRouteRoute = StoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsIndexRoute = ExpeditionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpeditionsRouteRoute,
} as any)
const ExpeditionsAntarcticaRoute = ExpeditionsAntarcticaRouteImport.update({
  id: '/antarctica',
  path: '/antarctica',
  getParentRoute: () => ExpeditionsRouteRoute,
} as any)
const ExpeditionsSouthernOceanRoute =
  ExpeditionsSouthernOceanRouteImport.update({
    id: '/southern-ocean',
    path: '/southern-ocean',
    getParentRoute: () => ExpeditionsRouteRoute,
  } as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesReadingTheIceRoute = StoriesReadingTheIceRouteImport.update({
  id: '/reading-the-ice',
  path: '/reading-the-ice',
  getParentRoute: () => StoriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expeditions': typeof ExpeditionsRouteRouteWithChildren
  '/stories': typeof StoriesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/expeditions/antarctica': typeof ExpeditionsAntarcticaRoute
  '/expeditions/southern-ocean': typeof ExpeditionsSouthernOceanRoute
  '/stories/reading-the-ice': typeof StoriesReadingTheIceRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/expeditions/antarctica': typeof ExpeditionsAntarcticaRoute
  '/expeditions/southern-ocean': typeof ExpeditionsSouthernOceanRoute
  '/stories/reading-the-ice': typeof StoriesReadingTheIceRoute
  '/expeditions': typeof ExpeditionsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expeditions': typeof ExpeditionsRouteRouteWithChildren
  '/stories': typeof StoriesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/expeditions/antarctica': typeof ExpeditionsAntarcticaRoute
  '/expeditions/southern-ocean': typeof ExpeditionsSouthernOceanRoute
  '/stories/reading-the-ice': typeof StoriesReadingTheIceRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expeditions'
    | '/stories'
    | '/about'
    | '/library'
    | '/expeditions/antarctica'
    | '/expeditions/southern-ocean'
    | '/stories/reading-the-ice'
    | '/expeditions/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/expeditions/antarctica'
    | '/expeditions/southern-ocean'
    | '/stories/reading-the-ice'
    | '/expeditions'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/expeditions'
    | '/stories'
    | '/about'
    | '/library'
    | '/expeditions/antarctica'
    | '/expeditions/southern-ocean'
    | '/stories/reading-the-ice'
    | '/expeditions/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpeditionsRouteRoute: typeof ExpeditionsRouteRouteWithChildren
  StoriesRouteRoute: typeof StoriesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/': {
      id: '/expeditions/'
      path: '/'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof ExpeditionsIndexRouteImport
      parentRoute: typeof ExpeditionsRouteRoute
    }
    '/expeditions/antarctica': {
      id: '/expeditions/antarctica'
      path: '/antarctica'
      fullPath: '/expeditions/antarctica'
      preLoaderRoute: typeof ExpeditionsAntarcticaRouteImport
      parentRoute: typeof ExpeditionsRouteRoute
    }
    '/expeditions/southern-ocean': {
      id: '/expeditions/southern-ocean'
      path: '/southern-ocean'
      fullPath: '/expeditions/southern-ocean'
      preLoaderRoute: typeof ExpeditionsSouthernOceanRouteImport
      parentRoute: typeof ExpeditionsRouteRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/reading-the-ice': {
      id: '/stories/reading-the-ice'
      path: '/reading-the-ice'
      fullPath: '/stories/reading-the-ice'
      preLoaderRoute: typeof StoriesReadingTheIceRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
  }
}

interface ExpeditionsRouteRouteChildren {
  ExpeditionsAntarcticaRoute: typeof ExpeditionsAntarcticaRoute
  ExpeditionsSouthernOceanRoute: typeof ExpeditionsSouthernOceanRoute
  ExpeditionsIndexRoute: typeof ExpeditionsIndexRoute
}

const ExpeditionsRouteRouteChildren: ExpeditionsRouteRouteChildren = {
  ExpeditionsAntarcticaRoute: ExpeditionsAntarcticaRoute,
  ExpeditionsSouthernOceanRoute: ExpeditionsSouthernOceanRoute,
  ExpeditionsIndexRoute: ExpeditionsIndexRoute,
}

const ExpeditionsRouteRouteWithChildren =
  ExpeditionsRouteRoute._addFileChildren(ExpeditionsRouteRouteChildren)

interface StoriesRouteRouteChildren {
  StoriesReadingTheIceRoute: typeof StoriesReadingTheIceRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteRouteChildren: StoriesRouteRouteChildren = {
  StoriesReadingTheIceRoute: StoriesReadingTheIceRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteRouteWithChildren = StoriesRouteRoute._addFileChildren(
  StoriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpeditionsRouteRoute: ExpeditionsRouteRouteWithChildren,
  StoriesRouteRoute: StoriesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
