import { Router, Request, Response } from 'express';
import { llmService } from '../services/llmService.js';

export const educationRouter = Router();

// POST /api/education/ask-tutor (Takes student question, forwards directly to live LLM)
educationRouter.post('/ask-tutor', async (req: Request, res: Response) => {
  const { question, level = 'kid' } = req.body;
  if (!question || typeof question !== 'string') {
    return res.status(400).json({ success: false, message: 'Question string is required' });
  }

  try {
    const result = await llmService.generateTutorResponse(question.trim(), level);
    res.json({
      success: true,
      data: result
    });
  } catch (error: any) {
    console.error('[EducationRouter] Ask tutor error:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Dr. Penguin tutor synthesis failed', 
      error: error?.message || error 
    });
  }
});

// POST /api/education/generate-quiz (Dynamic quiz questions generated by live LLM)
educationRouter.post('/generate-quiz', async (req: Request, res: Response) => {
  const { topic = 'General Antarctica', difficulty = 'medium' } = req.body;

  try {
    const questions = await llmService.generateQuizQuestions(topic, difficulty);
    res.json({
      success: true,
      topic,
      difficulty,
      data: questions
    });
  } catch (error: any) {
    console.error('[EducationRouter] Generate quiz error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate dynamic quiz',
      error: error?.message || error
    });
  }
});
